### ISSUE TITLE
minor readme correction?

### ISSUE THREAD

**Issue by sandro-pasquali** [leodutra/simpleflakes#1]
In the example showing the function signature for `simpleflake` I see this: `,random_bits=23-bit random,`.

Is that supposed to be `32-bit`?

**Comment by leodutra** [comment]
No, simpleflake is composed of 41 bit timestamp + 23 random bits (64 bits).
The official python library uses 64 bits too, so for compliance, that had been kept.

**Comment by sandro-pasquali** [comment]
Thank you.
